# Generated by Django 2.2.2 on 2019-06-21 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='category name')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A brief title of the expense', max_length=100, verbose_name='Title')),
                ('bill_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Bill Date')),
                ('image', models.ImageField(blank=True, help_text='Upload an Image', max_length=16384, null=True, upload_to='expense_image/', verbose_name='Image')),
                ('description', models.TextField(blank=True, help_text='Enter the Description for the type of expense', verbose_name='Description')),
                ('cost', models.PositiveSmallIntegerField(help_text='Enter the Amount Expended', verbose_name='Expenditure Cost')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.Category', verbose_name='Category')),
                ('user', models.ForeignKey(help_text='Choose the User to whom this expense belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(auto_now_add=True, verbose_name='End Date')),
                ('title', models.CharField(help_text=' title of the Budget', max_length=100, verbose_name='Title')),
                ('cost', models.PositiveSmallIntegerField(help_text='Enter the Budget amount:', verbose_name='Budget Cost')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.Category')),
                ('user', models.ForeignKey(help_text='Choose the User to whom this budget belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
