# Generated by Django 2.2.2 on 2019-06-21 09:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 21, 9, 16, 46, 924274, tzinfo=utc), verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(help_text='Choose the User to whom this budget belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(help_text='Choose the User to whom this expense belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
